[0m01:44:15.170121 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111145e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111873b60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111873f20>]}


============================== 01:44:15.173352 | 30225fee-7a47-499d-9a8e-78627cfe1f06 ==============================
[0m01:44:15.173352 [info ] [MainThread]: Running with dbt=1.9.3
[0m01:44:15.173655 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/gabrielbraga/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt ls', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m01:44:15.173923 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gabrielbraga/Library/CloudStorage/OneDrive-Pessoal/Documentos/Material de Estudo/DBT/projeto_dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:44:15.175531 [debug] [MainThread]: Resource report: {"command_name": "list", "command_success": false, "command_wall_clock_time": 0.049691666, "process_in_blocks": "0", "process_kernel_time": 0.163249, "process_mem_max_rss": "97157120", "process_out_blocks": "0", "process_user_time": 0.60398}
[0m01:44:15.175843 [debug] [MainThread]: Command `dbt ls` failed at 01:44:15.175797 after 0.05 seconds
[0m01:44:15.176018 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111145e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1115d26c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118a8320>]}
[0m01:44:15.176170 [debug] [MainThread]: Flushing usage events
[0m01:44:15.724282 [debug] [MainThread]: An error was encountered while trying to flush usage events
